W4D2/ninetynine_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
end

W4D2/ninetynine_cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord
  COLORS = %w(red orange yellow green blue indigo violet brown grey white black).freeze
  validates :color, presence: true, inclusion: { in: COLORS }
  validates :birth_date, presence: true
  validates :name, presence: true
  validates :sex, presence: true, inclusion: { in: %w(M F) }
  validates :description, presence: true

  has_many :cat_requests,
    class_name: :CatRentalRequest,
    foreign_key: :cat_id

  def age
    age = Date.today.year - birth_date.year
    age -= 1 if Date.today < birth_date + age.years
    age
  end
end

W4D2/ninetynine_cats/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ApplicationRecord
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validate :overlapping_requests, on: :create

  belongs_to :cat,
    class_name: :Cat,
    foreign_key: :cat_id,
    dependent: :destroy

    def overlapping_requests
      p "test"
      requests = CatRentalRequest.where(cat_id: cat_id)
        .where("'#{end_date}' <= cat_rental_requests.start_date AND '#{start_date}' <= cat_rental_requests.end_date")

      requests.empty?
    end

    def overlapping_approved_requests

    end

end

W4D2/ninetynine_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

W4D2/ninetynine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages, status: 418
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])

    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :birth_date, :sex, :description, :color)
  end

end

W4D2/ninetynine_cats/app/views/cats/_form.html.erb
<% if type == :edit %>
  <% action_url = cat_url(cat) %>
  <% button_value = 'Update Cat' %>
<% elsif type == :new %>
  <% action_url = cats_url %>
  <% button_value = 'Create Cat' %>
<% end %>

<form action="<%= action_url %>" method="post">
  <% if type == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  
  <p>Name:
    <input id="name" type="text" name="cat[name]" value= "<%= cat.name %>"/>
  </p>

  <p>Color:
    <select name="cat[color]">
      <option disabled selected>Please choose a color</option>
      <% Cat::COLORS.each do |color| %>
        <option value="<%= color %>" <%= cat.color == color ? "selected" : "" %>>
          <%= color %></option>
      <% end %>
    </select>
  </p>

  <p>Gender:
    <input type="radio" id="male"
     name="cat[sex]" value="M" <%= cat.sex == "M" ? "checked" : "" %>>
    <label for="male">M</label>

    <input type="radio" id="female"
     name="cat[sex]" value="F" <%= cat.sex == "F" ? "checked" : "" %>>
    <label for="female">F</label>
  </p>

  <p>Birthday:
    <input id="birthdate" type="date" name="cat[birth_date]" value= "<%= cat.birth_date %>"/>
  </p>

  <p>Description:
    <textarea name="cat[description]"><%= cat.description %></textarea>
  </p>

  <button type="submit" name="button"><%= button_value %></button>
</form>

W4D2/ninetynine_cats/app/views/cats/edit.html.erb
<%= render 'form', cat: @cat, type: :edit %>

W4D2/ninetynine_cats/app/views/cats/index.html.erb
<h1>KEEEEETTTTTTYYYYYY CAAAAAATTTTTTTSSSSSS</h1>

<% @cats.each do |cat| %>
  <h3><%= link_to cat.name, cat_url(cat) %></h3>
  <ul>
    <li>color: <%= cat.color %></li>
    <li>sex: <%= cat.sex %></li>
    <li>birth date: <%= cat.birth_date %></li>
    <li>age: <%= cat.age %></li>
  </ul>
    <p><%= cat.description  %></p>
<% end %>

W4D2/ninetynine_cats/app/views/cats/new.html.erb
<%= render 'form', cat: @cat, type: :new %>

<!-- 
<form action="/cats" method="post">
  <p>Name:
    <input id="name" type="text" name="cat[name]"/>
  </p>

  <%# colors = %w(red orange yellow green blue indigo violet brown grey white black) %>
  <p>Color:
    <select name="cat[color]">
      <option disabled selected>Please choose a color</option>
      <%# colors.each do |color| %>
        <option value=<%#= color %>><%#= color %></option>
      <%# end %>
    </select>
  </p>

  <p>Gender:
    <input type="radio" id="male"
     name="cat[gender]" value="M">
    <label for="male">M</label>

    <input type="radio" id="female"
     name="cat[gender]" value="F">
    <label for="female">F</label>
  </p>

  <p>Birthday:
    <input id="birthdate" type="date" name="cat[birth_date]"/>
  </p>

  <p>Description:
    <textarea name="cat[description]"></textarea>
  </p>

  <button type="submit" name="button">Create Cat</button>
</form> -->

W4D2/ninetynine_cats/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<table>
  <tr>
    <td>color:</td>
    <td><%= @cat.color %></td>
  </tr>
  <tr>
    <td>sex:</td>
    <td><%= @cat.sex %></td>
  </tr>
  <tr>
    <td>birth date:</td>
    <td><%= @cat.birth_date %></td>
  </tr>
  <tr>
    <td>age:</td>
    <td><%= @cat.age %></td>
  </tr>
</table>

  <p><%= @cat.description  %></p>

<%= link_to 'Cats Index', cats_url %>