W4D4/music_app/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :destroy, :new]
  resources :bands
  resources :albums

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

W4D4/music_app/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  band_id    :integer          not null
#  title      :string           not null
#  year       :integer          not null
#  live       :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  validates :band_id, :title, :year, presence: true

  belongs_to :band,
    class_name: :Band,
    foreign_key: :band_id,
    primary_key: :id
end

W4D4/music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
    class_name: :Album,
    foreign_key: :band_id,
    primary_key: :id

end

W4D4/music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(email, password)
    user = self.find_by(email: email)
    user && user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

W4D4/music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end
end

W4D4/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :logged_in?, :current_user, :logout!

  def log_in_user!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?(user)
    !!current_user
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end
end

W4D4/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to bands_url
    else
      flash[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def new
    render :new
  end

  def edit
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def update
  end

  def destroy
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

W4D4/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?(current_user)
      redirect_to user_url(current_user.id)
    else
      render :new
    end
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if @user
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = ["Invalid login!"]
      render :new
    end
  end

  def destroy
    logout!
    flash[:success] = 'Suceessfully logged out!'
    redirect_to new_user_url
  end
end

W4D4/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if logged_in?(current_user)
      redirect_to user_url(current_user.id)
    else
      render :new
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash[:error] = @user.errors.full_messages
      render :new
    end
  end

  def show

  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

W4D4/music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

W4D4/music_app/app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}' />".html_safe
  end
end

W4D4/music_app/app/helpers/bands_helper.rb
module BandsHelper
end

W4D4/music_app/app/views/bands/create.html.erb
<h1>Bands#create,</h1>
<p>Find me in app/views/bands/create,.html.erb</p>

W4D4/music_app/app/views/bands/destroy.html.erb
<h1>Bands#destroy</h1>
<p>Find me in app/views/bands/destroy.html.erb</p>

W4D4/music_app/app/views/bands/edit.html.erb
<h1>Bands#edit,</h1>
<p>Find me in app/views/bands/edit,.html.erb</p>

W4D4/music_app/app/views/bands/index.html.erb
<h2>Check out these awesome bands!</h2>

<% Band.all.each do |band| %>
  <p>
    <a href='<%= band_url(band) %>'><%= band.name %></a>
  </p>
<% end %>

W4D4/music_app/app/views/bands/new.html.erb
<h1>Bands#new,</h1>
<p>Find me in app/views/bands/new,.html.erb</p>

W4D4/music_app/app/views/bands/show.html.erb
<h2>Welcome to <%= @band.name %>'s page</h2>

<% @band.albums.each do |album| %>
  <p>
    <a href='<%= album_url(album) %>'><%= album.title %></a>
  </p>
<% end %>

<p>
  <a href='<%= bands_url %>'>View All Bands</a>
  <a href='<%= user_url %>'>Back to My Page</a>
</p>

W4D4/music_app/app/views/bands/update.html.erb
<h1>Bands#update,</h1>
<p>Find me in app/views/bands/update,.html.erb</p>

W4D4/music_app/app/views/layouts/_form.html.erb
<h2><%= header_text %></h2>

<form class="" action='<%= submit_url %>' method="POST">

  <br>

  <%= auth_token %>

  <label for="">Email:
    <input type="text" name="user[email]" value="">
  </label>

  <br>

  <label for="">Password:
    <input type="password" name="user[password]" value="">
  </label>

  <br>

  <input type="submit" value='<%= header_text %>'>

</form>

<br>

<a href='<%= alt_button_url %>'><%= alt_text %></a>

W4D4/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Erica+One|Henny+Penny|Luckiest+Guy|Poiret+One|Ribeye+Marrow|Sacramento" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <header class="application_header">
    <h1>&#9834; Music App &#9835;</h1>

    <% if logged_in?(@user) %>
    <section class="welcome">
      <p>Welcome, <%= current_user.email %>!</p>
        <form action='<%= session_url %>' method="POST">
          <%= auth_token %>
          <input type="hidden" name="_method" value="DELETE" />
          <input type="submit" value="logout">
        </form>
    </section>
    <% end %>
  </header>

  <body>
    <%= yield %>
  </body>
</html>